### ISSUE TITLE
eror pnpm run build

### ISSUE THREAD

**Issue by techwiz37** [enjidev/enji.dev#37]
enji.dev:db:generate: > enji.dev@0.1.0 db:generate /root/por/apps/enji.dev
enji.dev:db:generate: > prisma generate
enji.dev:db:generate:
remark-plugins:build:
remark-plugins:build: > remark-plugins@0.1.0 build /root/por/packages/remark-plugins
remark-plugins:build: > tsup --env.NODE_ENV production
remark-plugins:build:
enji.dev:db:generate: sh: 1: prisma: not found
enji.dev:db:generate:  ELIFECYCLE  Command failed.
enji.dev:db:generate:  WARN   Local package.json exists, but node_modules missing, did you mean to install?
remark-plugins:build: sh: 1: tsup: not found
remark-plugins:build:  ELIFECYCLE  Command failed.
remark-plugins:build:  WARN   Local package.json exists, but node_modules missing, did you mean to install?
enji.dev:db:generate: ERROR: command finished with error: command (/root/por/apps/enji.dev) /root/.nvm/versions/node/v18.10.0/bin/pnpm run db:generate exited (1)
enji.dev#db:generate: command (/root/por/apps/enji.dev) /root/.nvm/versions/node/v18.10.0/bin/pnpm run db:generate exited (1)

 Tasks:    0 successful, 3 total
Cached:    0 cached, 3 total
  Time:    2.564s
Failed:    enji.dev#db:generate

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
root@host:~/por#

**Comment by zakjanzi** [comment]
Did you figure out how to run this project?

**Comment by enjidev** [comment]
Hi, I just added the instructions for running this project in the README.
