### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by altafpasha** [enjidev/enji.dev#45]
Hi im getting error when i click on blogs 

![image](https://github.com/enjidev/enji.dev/assets/121569160/282f02b6-2a44-4760-bba8-5af76db32315)

**Comment by SkyrimTB** [comment]
I think it's because the failure connection of MongoDB, but I did not find the solution too.

**Comment by qlAD** [comment]
> Hi im getting error when i click on blogs
> 
> ![image](https://private-user-images.githubusercontent.com/121569160/344269103-282f02b6-2a44-4760-bba8-5af76db32315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTMxNzUsIm5iZiI6MTcyODM5Mjg3NSwicGF0aCI6Ii8xMjE1NjkxNjAvMzQ0MjY5MTAzLTI4MmYwMmI2LTJhNDQtNDc2MC1iYmE4LTVhZjc2ZGIzMjMxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMzA3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjJkOWVjYmMyYWVmYTg5MzdjYTI0ZjI5YzdiYjE5ZDRiNmUxYTZjMmY3MzZmNzkzMTc1MWYyYjI0N2NjY2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OxzbWwhQvp0tAoSJZCiB6kMHcJiApM1b1ingQ_3c0tI)

Hello, this is probably a database problem. Please check your project error message in the terminal.

If it prompts "**Error parsing connection string: Database must be defined in the connection string**", you need to specify the database name of the connection string. When directly copying, the database name is not specified. The complete string should be "`mongodb+srv://<username>:<password>@<cluster-url>/<database>?retryWrites=true&w=majority&appName=<cluster-name>`".

If the prompt is "**Server selection timeout: No available servers**", it means that there is a connection problem, which may be a problem with the network, permissions, etc. Generally, it may be that the IP whitelist has not been added.
