### ISSUE TITLE
Deployment Issues on Vercel

### ISSUE THREAD

**Issue by Jaomar92** [enjidev/enji.dev#49]
Hi,
I was wondering if you could walk through the steps to deploy via vercel? 

Locally runs fine. But on vercel 

Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.

please advice, thank you

**Comment by enjidev** [comment]
can you try latest changes, i have updated some packages and config. you can reopen this if the issue still persist, also attach some additional information
